version: '3.8'

services:
  database:
    image: postgis/postgis:15-3.3
    container_name: treewar_db
    environment:
      POSTGRES_USER: treewar
      POSTGRES_PASSWORD: treewar_password
      POSTGRES_DB: treewar_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
